name: IF-Block
main: com.rabbitmint.if_Block
version: 2.3
api-version: 1.20
author: RabbitMint
description: "플레이어가 특정 블럭을 밟으면 명령어를 실행하는 플러그인"
commands:
  if-block:
    description: 블럭을 설정하거나 리셋하는 명령어
    usage: /if-block <설정|리셋> <블럭이름>
    permission: if_block.use
    permission-message: "이 명령어를 사용할 권한이 없습니다."
permissions:
  if_block.use:
    description: if-block 명령어를 사용할 수 있는 권한
    default: true
